name: "小智 AI Server 最简化版"
version: "0.3.12"
slug: "xiaozhi_esp32_server"
description: "小智 AI Server 最简化版 - 提供语音识别、对话和控制功能，支持与ESP32设备通信"
url: "https://github.com/waxgourd-ha/waxgourd-addons"
arch:
  - aarch64
  - amd64
startup: application
boot: manual
ports:
  8000/tcp: 8000
ports_description:
  8000/tcp: "WebSocket服务端口"
map:
  - addon_config:rw
host_network: false
init: false
watchdog: "tcp://[HOST]:[PORT:8000]"
journald: true
image: wghaos/xiaozhi-esp32-server-{arch}
